# Generated by Django 4.2.2 on 2023-06-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('status', models.TextField(blank=True, choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], null=True, verbose_name='Статус')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('end_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата завершения')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата изменения ')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'todolist',
            },
        ),
    ]
