# Generated by Django 4.2.2 on 2023-07-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statustodo',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='typetodo',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Тип'),
        ),
    ]
