# Generated by Django 4.2.2 on 2023-06-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.TextField(blank=True, choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='Новая', null=True, verbose_name='Статус'),
        ),
    ]
