# Generated by Django 4.2.2 on 2023-07-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_project_options_alter_project_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
