# Generated by Django 4.2.2 on 2023-07-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_todolist_type_todo_todolist_type_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='type_todo',
            field=models.ManyToManyField(blank=True, related_name='тип', to='webapp.typetodo'),
        ),
    ]
