# Generated by Django 4.2.2 on 2023-07-25 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0005_alter_todolist_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='User_project_name',
            field=models.ManyToManyField(blank=True, related_name='project', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
